apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - Ingress/webts-dev-ingress.yml
#  - HTTProutes/webts-dev.yml

patchesStrategicMerge:
  - Deployements/nginx-php-patch.yaml
