apiVersion: v1
kind: Service
metadata:
  name: homebridge
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - name: http
      port: 8582
      targetPort: 8582
      protocol: TCP
  type: ClusterIP
