apiVersion: v1
kind: Service
metadata:
  name: homekit
  namespace: homebridge
spec:
  selector:
    app: homebridge
  ports:
    - name: homekit
      port: 63300
      targetPort: 63300
      protocol: TCP
  type: LoadBalancer
