apiVersion: v1
data:
  my.cnf: |
    #
    # This group is read both both by the client and the server
    # use it for options that affect everything
    #
    [client]
    port            = 3306
    socket          = /var/tmp/mysql.sock

    #
    # include all files from the config directory
    #
    !includedir /etc/my.cnf.d

    [mysqld]
    port            = 3306
    socket          = /var/tmp/mysql.sock
    log-error       = /var/lib/mysql/mysqld.log
    datadir         = /var/lib/mysql
    basedir         = /usr
    pid-file        = /var/run/mysqld/mysqld.pid
    log_bin_trust_function_creators = 1
    lower-case-table-names=0
    #default-authentication-plugin = caching_sha2_password
    user = mysql
    character-set-server = latin1
kind: ConfigMap
metadata:
  name: my-cnf
