apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-prod-tls
  namespace: argocd
spec:
  parentRefs:
    - name: scdb-gateway
      namespace: default
      sectionName: tls-prod-argocd
  hostnames:
    - argocd.prod.home.dblanchet.net
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
