apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: homebridge
          image: harbor.prod.home.dblanchet.net/scdb/homebridge:node24.13.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8581
              name: http
              protocol: TCP
            - containerPort: 62300
              name: hk-62300
              protocol: TCP
            - containerPort: 62301
              name: hk-62301
              protocol: TCP
            - containerPort: 62302
              name: hk-62302
              protocol: TCP
            - containerPort: 62303
              name: hk-62303
              protocol: TCP
            - containerPort: 62304
              name: hk-62304
              protocol: TCP
            - containerPort: 62305
              name: hk-62305
              protocol: TCP
            - containerPort: 62306
              name: hk-62306
              protocol: TCP
            - containerPort: 62307
              name: hk-62307
              protocol: TCP
            - containerPort: 62308
              name: hk-62308
              protocol: TCP
            - containerPort: 62309
              name: hk-62309
              protocol: TCP
            - containerPort: 62310
              name: hk-62310
              protocol: TCP
            - containerPort: 62311
              name: hk-62311
              protocol: TCP
            - containerPort: 62312
              name: hk-62312
              protocol: TCP
            - containerPort: 62313
              name: hk-62313
              protocol: TCP
            - containerPort: 62314
              name: hk-62314
              protocol: TCP
            - containerPort: 62315
              name: hk-62315
              protocol: TCP
            - containerPort: 62316
              name: hk-62316
              protocol: TCP
            - containerPort: 62317
              name: hk-62317
              protocol: TCP
            - containerPort: 62318
              name: hk-62318
              protocol: TCP
            - containerPort: 62319
              name: hk-62319
              protocol: TCP
            - containerPort: 62320
              name: hk-62320
              protocol: TCP
            - containerPort: 62321
              name: hk-62321
              protocol: TCP
            - containerPort: 62322
              name: hk-62322
              protocol: TCP
            - containerPort: 62323
              name: hk-62323
              protocol: TCP
            - containerPort: 62324
              name: hk-62324
              protocol: TCP
            - containerPort: 62325
              name: hk-62325
              protocol: TCP
            - containerPort: 62326
              name: hk-62326
              protocol: TCP
            - containerPort: 62327
              name: hk-62327
              protocol: TCP
            - containerPort: 62328
              name: hk-62328
              protocol: TCP
            - containerPort: 62329
              name: hk-62329
              protocol: TCP
            - containerPort: 62330
              name: hk-62330
              protocol: TCP
            - containerPort: 62331
              name: hk-62331
              protocol: TCP
            - containerPort: 62332
              name: hk-62332
              protocol: TCP
            - containerPort: 62333
              name: hk-62333
              protocol: TCP
            - containerPort: 62334
              name: hk-62334
              protocol: TCP
            - containerPort: 62335
              name: hk-62335
              protocol: TCP
            - containerPort: 62336
              name: hk-62336
              protocol: TCP
            - containerPort: 62337
              name: hk-62337
              protocol: TCP
            - containerPort: 62338
              name: hk-62338
              protocol: TCP
            - containerPort: 62339
              name: hk-62339
              protocol: TCP
            - containerPort: 62340
              name: hk-62340
              protocol: TCP
            - containerPort: 62341
              name: hk-62341
              protocol: TCP
            - containerPort: 62342
              name: hk-62342
              protocol: TCP
            - containerPort: 62343
              name: hk-62343
              protocol: TCP
            - containerPort: 62344
              name: hk-62344
              protocol: TCP
            - containerPort: 62345
              name: hk-62345
              protocol: TCP
            - containerPort: 62346
              name: hk-62346
              protocol: TCP
            - containerPort: 62347
              name: hk-62347
              protocol: TCP
            - containerPort: 62348
              name: hk-62348
              protocol: TCP
            - containerPort: 62349
              name: hk-62349
              protocol: TCP
            - containerPort: 62350
              name: hk-62350
              protocol: TCP
            - containerPort: 62351
              name: hk-62351
              protocol: TCP
            - containerPort: 62352
              name: hk-62352
              protocol: TCP
            - containerPort: 62353
              name: hk-62353
              protocol: TCP
            - containerPort: 62354
              name: hk-62354
              protocol: TCP
            - containerPort: 62355
              name: hk-62355
              protocol: TCP
            - containerPort: 62356
              name: hk-62356
              protocol: TCP
            - containerPort: 62357
              name: hk-62357
              protocol: TCP
            - containerPort: 62358
              name: hk-62358
              protocol: TCP
            - containerPort: 62359
              name: hk-62359
              protocol: TCP
            - containerPort: 62360
              name: hk-62360
              protocol: TCP
            - containerPort: 62361
              name: hk-62361
              protocol: TCP
            - containerPort: 62362
              name: hk-62362
              protocol: TCP
            - containerPort: 62363
              name: hk-62363
              protocol: TCP
            - containerPort: 62364
              name: hk-62364
              protocol: TCP
            - containerPort: 62365
              name: hk-62365
              protocol: TCP
            - containerPort: 62366
              name: hk-62366
              protocol: TCP
            - containerPort: 62367
              name: hk-62367
              protocol: TCP
            - containerPort: 62368
              name: hk-62368
              protocol: TCP
            - containerPort: 62369
              name: hk-62369
              protocol: TCP
            - containerPort: 62370
              name: hk-62370
              protocol: TCP
            - containerPort: 62371
              name: hk-62371
              protocol: TCP
            - containerPort: 62372
              name: hk-62372
              protocol: TCP
            - containerPort: 62373
              name: hk-62373
              protocol: TCP
            - containerPort: 62374
              name: hk-62374
              protocol: TCP
            - containerPort: 62375
              name: hk-62375
              protocol: TCP
            - containerPort: 62376
              name: hk-62376
              protocol: TCP
            - containerPort: 62377
              name: hk-62377
              protocol: TCP
            - containerPort: 62378
              name: hk-62378
              protocol: TCP
            - containerPort: 62379
              name: hk-62379
              protocol: TCP
            - containerPort: 62380
              name: hk-62380
              protocol: TCP
            - containerPort: 62381
              name: hk-62381
              protocol: TCP
            - containerPort: 62382
              name: hk-62382
              protocol: TCP
            - containerPort: 62383
              name: hk-62383
              protocol: TCP
            - containerPort: 62384
              name: hk-62384
              protocol: TCP
            - containerPort: 62385
              name: hk-62385
              protocol: TCP
            - containerPort: 62386
              name: hk-62386
              protocol: TCP
            - containerPort: 62387
              name: hk-62387
              protocol: TCP
            - containerPort: 62388
              name: hk-62388
              protocol: TCP
            - containerPort: 62389
              name: hk-62389
              protocol: TCP
            - containerPort: 62390
              name: hk-62390
              protocol: TCP
            - containerPort: 62391
              name: hk-62391
              protocol: TCP
            - containerPort: 62392
              name: hk-62392
              protocol: TCP
            - containerPort: 62393
              name: hk-62393
              protocol: TCP
            - containerPort: 62394
              name: hk-62394
              protocol: TCP
            - containerPort: 62395
              name: hk-62395
              protocol: TCP
            - containerPort: 62396
              name: hk-62396
              protocol: TCP
            - containerPort: 62397
              name: hk-62397
              protocol: TCP
            - containerPort: 62398
              name: hk-62398
              protocol: TCP
            - containerPort: 62399
              name: hk-62399
              protocol: TCP
            - containerPort: 5353
              name: mdns
              protocol: UDP
          env:
            # tu peux en ajouter selon ta config actuelle du conteneur
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Montreal"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8581"
          volumeMounts:
            - name: config
              mountPath: /homebridge
            - name: homebridge-env
              mountPath: /usr/local/bin/homebridge.env
              subPath: homebridge.env
            - name: backups
              mountPath: /homebridge/backups/instance-backups
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homebridge-config
        - name: homebridge-env
          configMap:
            name: homebridge-env
            defaultMode: 0644
        - name: backups
          persistentVolumeClaim:
            claimName: homebridge-backups
      terminationGracePeriodSeconds: 30
