apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebridge
  namespace: homebridge
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: homebridge
  template:
    metadata:
      labels:
        app: homebridge
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: homebridge
          image: harbor.prod.home.dblanchet.net/scdb/homebridge:node24.14.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8581
              name: http
              protocol: TCP
            - containerPort: 62300
              name: hk-62300
              protocol: TCP
#            - containerPort: 5353
#              name: mdns
#              protocol: UDP
          env:
            # tu peux en ajouter selon ta config actuelle du conteneur
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: "America/Montreal"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8581"
          volumeMounts:
            - name: config
              mountPath: /homebridge
            - name: homebridge-env
              mountPath: /usr/local/bin/homebridge.env
              subPath: homebridge.env
            - name: backups
              mountPath: /homebridge/backups/instance-backups
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: homebridge-config
        - name: homebridge-env
          configMap:
            name: homebridge-env
            defaultMode: 0644
        - name: backups
          persistentVolumeClaim:
            claimName: homebridge-backups
      terminationGracePeriodSeconds: 30
