apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ReferenceGrants/allow-gateway-to-certs.yaml
  - PersistentVolumeClaim/db-backup.yml
  - HTTPRoutes/webts-secure-route.yaml

#patchesStrategicMerge:
#  - Deployements/nginx-php-patch.yaml
