apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webts-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:DanielBlanchet/scdb-cluster-gitops.git
    targetRevision: main
    path: apps/WebTs/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: webts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
