apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-backups
  namespace: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
