apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: prod-web-route
  namespace: webts
spec:
  parentRefs:
    - name: scdb-gateway
      namespace: default
      sectionName: tls
  hostnames:
    - webts.prod.home.dblanchet.net
  rules:
    - backendRefs:
        - name: webts-web-svc
          port: 4443
