apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespaces/namespace.yaml
  - PersistentVolumeClaim/homebridge-backups-pvc.yaml
  - PersistentVolumeClaim/homebridge-config-pvc.yaml
  - ConfigMaps/homebridge-env.yml
