apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespaces/namespace.yaml
  - ConfigMaps/default-conf.yaml
  - ConfigMaps/nginx-conf.yaml
  - PersistentVolumeClaim/pvc-test.yaml
  - Deployements/test-web.yaml
  - Services/test-web-svc.yaml
  - HTTProutes/HTTPRoute.yaml
