apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ConfigMaps/default-conf.yaml
  - ConfigMaps/nginx-conf.yaml
  - Deployements/test-web.yaml
  - Services/service.yaml
  - HTTProutes/HTTPRoute.yaml
