apiVersion: v1
data:
  homebridge.env: |
    HOMEBRIDGE_CONFIG_UI_TERMINAL=1
    export HOMEBRIDGE_CONFIG_UI_TERMINAL
    HOMEBRIDGE_DISABLE_SUDO=1
    export HOMEBRIDGE_DISABLE_SUDO
    HOMEBRIDGE_CONFIG_UI_DISABLE_SUDO=1
    export HOMEBRIDGE_CONFIG_UI_DISABLE_SUDO
    HOMEBRIDGE_ALLOW_INSECURE_PLUGINS=1
    export HOMEBRIDGE_ALLOW_INSECURE_PLUGINS
    HOMEBRIDGE_CONFIG_UI_ALLOW_UNVERIFIED_PLUGINS=1
    export HOMEBRIDGE_CONFIG_UI_ALLOW_UNVERIFIED_PLUGINS
    export HOMEBRIDGE_CONFIG_UI_PORT=8582
    DEBUG=0
    export DEBUG
kind: ConfigMap
metadata:
  name: homebridge-env
